### ISSUE TITLE
ユーザー名の読み上げ(Read Name)の括弧の扱いについて

### ISSUE THREAD

**Issue by to** [advancedbear/TwitchTalkApp#2]
現在、棒読みちゃんに送信するユーザー名は、以下コードにて括弧でラップされています。

`nMessage = message+' ('+from+')';`

棒読みちゃんで配信者設定をオンにしていると「a)」などは声質指定のコマンドとして認識されるため、ユーザー名の末尾が消えてしまうことがあります。(具体的には末尾がybhdartgの名前)
末尾が変化してしまうと、読み上げも変わってしまいますし、辞書を使った置換も支障が生じます((tanaka)がtanakaでヒットしなくなる)。
括弧でラップするのを止める、末尾の括弧を除く、他の記号でラップする、などの対応をされてはいかがですか？
(うっ、えらそう…すばらしいソフトウェアの公開、ナイスです！)

**Comment by advancedbear** [comment]
あー、棒読みちゃんの配信者モードって行頭じゃなくても判定されるんでしたっけか。
文末になるから平気かなと思ってましたが必ずしもそうではないわけですね。

少し変更しておこうと思います。
