### ISSUE TITLE
Ichiro が選択肢に出てこない

### ISSUE THREAD

**Issue by sergei-ogan** [advancedbear/TwitchTalkApp#6]
Windows の設定では正しく Ichiro の音声が確認できますが、このアプリのJP言語設定で SAPI5 を選択した際の OPTION には Ichiro がありません。
I can choose voice type to "Ichiro" in Windows Configuration. but there is not exists that Ichiro option in this app.

Windows
![SS_007](https://user-images.githubusercontent.com/622793/144610035-8b900b32-09fd-4375-8fcd-4c689117df9f.JPG)

TwitchTalkApp
![SS_006](https://user-images.githubusercontent.com/622793/144610001-9433aff0-d293-4cd6-8130-c66ee102cacc.JPG)

これは選択肢に追加漏れでしょうか？それとも何らかの不具合？
is this issue? or default? i want to choose Ichiro voice.

**Comment by advancedbear** [comment]
@ogaaaan 
Microsoft IchiroはMicrosft UWP環境向けの音声合成エンジンなので、Chromiumなどの非UWPアプリケーションからはSAPI5として利用することが出来ません。
TwitchTalkAppはChromiumベースでUWPアプリケーションではないため、Microsoft Ichiroを使うことは出来ません。
今後、利用できるように修正されることもありません。
